# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 877c72ce572efce38b7a73f5fc8bd9f96c344114b52b94f2f5c22f2e27ba41f475e7019b04783a708e2a7126da1b848ce10c8a1aef33f79905d2a9223a06b49a

test:
  secret_key_base: c156c5a5ddf48793cf8cbb60aa12577bb1189b378e2afdf71cd770cc9e988e656b774befd2301316b6288932f32023b8075498e4a17c7403f52ca5a08986c16e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
